package com.deencompanion.app.domain.model



data class Surah(
    val number: Int,
    val nameArabic: String,
    val nameEnglish: String,
    val nameTransliteration: String,
    val versesCount: Int,
    val revelationType: String
) {
    companion object {
        val ALL_SURAHS = listOf(
            Surah(1, "الفاتحة", "The Opening", "Al-Fatihah", 7, "Meccan"),
            Surah(2, "البقرة", "The Cow", "Al-Baqarah", 286, "Medinan"),
            Surah(3, "آل عمران", "The Family of Imran", "Ali 'Imran", 200, "Medinan"),
            Surah(4, "النساء", "The Women", "An-Nisa", 176, "Medinan"),
            Surah(5, "المائدة", "The Table Spread", "Al-Ma'idah", 120, "Medinan"),
            Surah(6, "الأنعام", "The Cattle", "Al-An'am", 165, "Meccan"),
            Surah(7, "الأعراف", "The Heights", "Al-A'raf", 206, "Meccan"),
            Surah(8, "الأنفال", "The Spoils of War", "Al-Anfal", 75, "Medinan"),
            Surah(9, "التوبة", "The Repentance", "At-Tawbah", 129, "Medinan"),
            Surah(10, "يونس", "Jonah", "Yunus", 109, "Meccan"),
            Surah(11, "هود", "Hud", "Hud", 123, "Meccan"),
            Surah(12, "يوسف", "Joseph", "Yusuf", 111, "Meccan"),
            Surah(13, "الرعد", "The Thunder", "Ar-Ra'd", 43, "Medinan"),
            Surah(14, "ابراهيم", "Abraham", "Ibrahim", 52, "Meccan"),
            Surah(15, "الحجر", "The Rocky Tract", "Al-Hijr", 99, "Meccan"),
            Surah(16, "النحل", "The Bee", "An-Nahl", 128, "Meccan"),
            Surah(17, "الإسراء", "The Night Journey", "Al-Isra", 111, "Meccan"),
            Surah(18, "الكهف", "The Cave", "Al-Kahf", 110, "Meccan"),
            Surah(19, "مريم", "Mary", "Maryam", 98, "Meccan"),
            Surah(20, "طه", "Ta-Ha", "Ta-Ha", 135, "Meccan"),
            Surah(21, "الأنبياء", "The Prophets", "Al-Anbiya", 112, "Meccan"),
            Surah(22, "الحج", "The Pilgrimage", "Al-Hajj", 78, "Medinan"),
            Surah(23, "المؤمنون", "The Believers", "Al-Mu'minun", 118, "Meccan"),
            Surah(24, "النور", "The Light", "An-Nur", 64, "Medinan"),
            Surah(25, "الفرقان", "The Criterion", "Al-Furqan", 77, "Meccan"),
            Surah(26, "الشعراء", "The Poets", "Ash-Shu'ara", 227, "Meccan"),
            Surah(27, "النمل", "The Ant", "An-Naml", 93, "Meccan"),
            Surah(28, "القصص", "The Stories", "Al-Qasas", 88, "Meccan"),
            Surah(29, "العنكبوت", "The Spider", "Al-Ankabut", 69, "Meccan"),
            Surah(30, "الروم", "The Romans", "Ar-Rum", 60, "Meccan"),
            Surah(31, "لقمان", "Luqman", "Luqman", 34, "Meccan"),
            Surah(32, "السجدة", "The Prostration", "As-Sajdah", 30, "Meccan"),
            Surah(33, "الأحزاب", "The Combined Forces", "Al-Ahzab", 73, "Medinan"),
            Surah(34, "سبأ", "Sheba", "Saba", 54, "Meccan"),
            Surah(35, "فاطر", "Originator", "Fatir", 45, "Meccan"),
            Surah(36, "يس", "Ya-Sin", "Ya-Sin", 83, "Meccan"),
            Surah(37, "الصافات", "Those who set the Ranks", "As-Saffat", 182, "Meccan"),
            Surah(38, "ص", "Sad", "Sad", 88, "Meccan"),
            Surah(39, "الزمر", "The Troops", "Az-Zumar", 75, "Meccan"),
            Surah(40, "غافر", "The Forgiver", "Ghafir", 85, "Meccan"),
            Surah(41, "فصلت", "Explained in Detail", "Fussilat", 54, "Meccan"),
            Surah(42, "الشورى", "The Consultation", "Ash-Shura", 53, "Meccan"),
            Surah(43, "الزخرف", "The Ornaments of Gold", "Az-Zukhruf", 89, "Meccan"),
            Surah(44, "الدخان", "The Smoke", "Ad-Dukhan", 59, "Meccan"),
            Surah(45, "الجاثية", "The Crouching", "Al-Jathiyah", 37, "Meccan"),
            Surah(46, "الأحقاف", "The Wind-Curved Sandhills", "Al-Ahqaf", 35, "Meccan"),
            Surah(47, "محمد", "Muhammad", "Muhammad", 38, "Medinan"),
            Surah(48, "الفتح", "The Victory", "Al-Fath", 29, "Medinan"),
            Surah(49, "الحجرات", "The Dwellings", "Al-Hujurat", 18, "Medinan"),
            Surah(50, "ق", "Qaf", "Qaf", 45, "Meccan"),
            Surah(51, "الذاريات", "The Winnowing Winds", "Adh-Dhariyat", 60, "Meccan"),
            Surah(52, "الطور", "The Mount", "At-Tur", 49, "Meccan"),
            Surah(53, "النجم", "The Star", "An-Najm", 62, "Meccan"),
            Surah(54, "القمر", "The Moon", "Al-Qamar", 55, "Meccan"),
            Surah(55, "الرحمن", "The Beneficent", "Ar-Rahman", 78, "Medinan"),
            Surah(56, "الواقعة", "The Inevitable", "Al-Waqi'ah", 96, "Meccan"),
            Surah(57, "الحديد", "The Iron", "Al-Hadid", 29, "Medinan"),
            Surah(58, "المجادلة", "The Pleading Woman", "Al-Mujadilah", 22, "Medinan"),
            Surah(59, "الحشر", "The Exile", "Al-Hashr", 24, "Medinan"),
            Surah(60, "الممتحنة", "She that is to be examined", "Al-Mumtahanah", 13, "Medinan"),
            Surah(61, "الصف", "The Ranks", "As-Saff", 14, "Medinan"),
            Surah(62, "الجمعة", "The Congregation", "Al-Jumu'ah", 11, "Medinan"),
            Surah(63, "المنافقون", "The Hypocrites", "Al-Munafiqun", 11, "Medinan"),
            Surah(64, "التغابن", "The Mutual Disillusion", "At-Taghabun", 18, "Medinan"),
            Surah(65, "الطلاق", "The Divorce", "At-Talaq", 12, "Medinan"),
            Surah(66, "التحريم", "The Prohibition", "At-Tahrim", 12, "Medinan"),
            Surah(67, "الملك", "The Sovereignty", "Al-Mulk", 30, "Meccan"),
            Surah(68, "القلم", "The Pen", "Al-Qalam", 52, "Meccan"),
            Surah(69, "الحاقة", "The Reality", "Al-Haqqah", 52, "Meccan"),
            Surah(70, "المعارج", "The Ascending Stairways", "Al-Ma'arij", 44, "Meccan"),
            Surah(71, "نوح", "Noah", "Nuh", 28, "Meccan"),
            Surah(72, "الجن", "The Jinn", "Al-Jinn", 28, "Meccan"),
            Surah(73, "المزمل", "The Enshrouded One", "Al-Muzzammil", 20, "Meccan"),
            Surah(74, "المدثر", "The Cloaked One", "Al-Muddaththir", 56, "Meccan"),
            Surah(75, "القيامة", "The Resurrection", "Al-Qiyamah", 40, "Meccan"),
            Surah(76, "الإنسان", "The Man", "Al-Insan", 31, "Medinan"),
            Surah(77, "المرسلات", "Those Sent Forth", "Al-Mursalat", 50, "Meccan"),
            Surah(78, "النبأ", "The Great News", "An-Naba", 40, "Meccan"),
            Surah(79, "النازعات", "Those who Drag Forth", "An-Nazi'at", 46, "Meccan"),
            Surah(80, "عبس", "He Frowned", "'Abasa", 42, "Meccan"),
            Surah(81, "التكوير", "The Overthrowing", "At-Takwir", 29, "Meccan"),
            Surah(82, "الانفطار", "The Cleaving", "Al-Infitar", 19, "Meccan"),
            Surah(83, "المطففين", "Defrauding", "Al-Mutaffifin", 36, "Meccan"),
            Surah(84, "الانشقاق", "The Sundering", "Al-Inshiqaq", 25, "Meccan"),
            Surah(85, "البروج", "The Mansions of the Stars", "Al-Buruj", 22, "Meccan"),
            Surah(86, "الطارق", "The Morning Star", "At-Tariq", 17, "Meccan"),
            Surah(87, "الأعلى", "The Most High", "Al-A'la", 19, "Meccan"),
            Surah(88, "الغاشية", "The Overwhelming", "Al-Ghashiyah", 26, "Meccan"),
            Surah(89, "الفجر", "The Dawn", "Al-Fajr", 30, "Meccan"),
            Surah(90, "البلد", "The City", "Al-Balad", 20, "Meccan"),
            Surah(91, "الشمس", "The Sun", "Ash-Shams", 15, "Meccan"),
            Surah(92, "الليل", "The Night", "Al-Lail", 21, "Meccan"),
            Surah(93, "الضحى", "The Morning Hours", "Ad-Duha", 11, "Meccan"),
            Surah(94, "الشرح", "The Relief", "Ash-Sharh", 8, "Meccan"),
            Surah(95, "التين", "The Fig", "At-Tin", 8, "Meccan"),
            Surah(96, "العلق", "The Clot", "Al-'Alaq", 19, "Meccan"),
            Surah(97, "القدر", "The Power", "Al-Qadr", 5, "Meccan"),
            Surah(98, "البينة", "The Clear Proof", "Al-Bayyinah", 8, "Medinan"),
            Surah(99, "الزلزلة", "The Earthquake", "Az-Zalzalah", 8, "Medinan"),
            Surah(100, "العاديات", "The Courser", "Al-'Adiyat", 11, "Meccan"),
            Surah(101, "القارعة", "The Calamity", "Al-Qari'ah", 11, "Meccan"),
            Surah(102, "التكاثر", "The Rivalry in World Increase", "At-Takathur", 8, "Meccan"),
            Surah(103, "العصر", "The Declining Day", "Al-'Asr", 3, "Meccan"),
            Surah(104, "الهمزة", "The Traducer", "Al-Humazah", 9, "Meccan"),
            Surah(105, "الفيل", "The Elephant", "Al-Fil", 5, "Meccan"),
            Surah(106, "قريش", "Quraysh", "Quraysh", 4, "Meccan"),
            Surah(107, "الماعون", "The Small Kindnesses", "Al-Ma'un", 7, "Meccan"),
            Surah(108, "الكوثر", "The Abundance", "Al-Kauthar", 3, "Meccan"),
            Surah(109, "الكافرون", "The Disbelievers", "Al-Kafirun", 6, "Meccan"),
            Surah(110, "النصر", "The Divine Support", "An-Nasr", 3, "Medinan"),
            Surah(111, "المسد", "The Palm Fiber", "Al-Masad", 5, "Meccan"),
            Surah(112, "الإخلاص", "The Sincerity", "Al-Ikhlas", 4, "Meccan"),
            Surah(113, "الفلق", "The Daybreak", "Al-Falaq", 5, "Meccan"),
            Surah(114, "الناس", "Mankind", "An-Nas", 6, "Meccan")
        )
    }
}